name: Actions

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    name: Build Cortijo Game
    runs-on: ubuntu-18.04
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Tests
      - name: Run tests
        uses: game-ci/unity-test-runner@v1.3
        with:
          unityVersion: 2019.4.14f1

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v0.10
        with:
          unityVersion: 2019.4.14f1
          targetPlatform: StandaloneLinux64

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: Build
